"
" {HOME}/etc/vimrc
"
" to use, add to ${HOME}/.vimrc:
"
"     source {HOME}/etc/vimrc
"

syntax on

" From http://jmcpherson.org/vimrc.html
set incsearch
set showmatch
set autoindent
set smartindent

" From http://people.smu.edu/jrobinet/howto/customize-vim.asp
set nocompatible
" show ruler and commands
set ruler
set showcmd
" use spaces instead of tabs
set sw=4
set sts=4
set ts=4
set et
