#!/usr/bin/sudo /bin/bash

CFG="/usr/lib/gtk-2.0/2.10.0/immodule-files.d/libgtk2.0-0.immodules"

[ ! -r $CFG ] && { echo "Cannot find file: $CFG" >&2; exit 1; }
perl -i.bak -ple 's/"\s*$/:en"/ if /"cedilla"/' $CFG

echo "Changes will take effect upon next start of the X server" >&2


